# Generated by Django 3.1.6 on 2021-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('DOING', 'Doing'), ('DONE', 'Done')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
